image:
  name: form
  repo: quanxiang
  tag: v0.7.0
namespace: ""
imagePullSecrets: lowcode
service:
  type: ClusterIP
  port: 80
  rpcPort: 0
nameOverride: ""
fullnameOverride: ""
websocket_hostname: ""
home_hostname: ""
portal_hostname: ""
serviceAccount:
  name: ""
podSecurityContext: {}
securityContext: {}
config:
  mysql:
    db: ""
    host: mysql.nginx-ingress.svc.cluster.local:3306
    user: root
    password: qxp1234
    log: true
  redis:
    addrs:
    - example-distributedrediscluster-0.nginx-ingress.svc.cluster.local:6379
    - example-distributedrediscluster-1.nginx-ingress.svc.cluster.local:6379
    - example-distributedrediscluster-2.nginx-ingress.svc.cluster.local:6379
    username: null
    password: qxp1234
  elastic:
    log: true
    host:
    - http://elasticsearch-client.nginx-ingress.svc.cluster.local:9200
  kafka:
    broker:
    - kafka.nginx-ingress.svc.cluster.local:9092
  mongo:
    hosts:
    - mongodb.nginx-ingress.svc.cluster.local:27017
    direct: false
    credential:
      authMechanism: SCRAM-SHA-1
      authSource: admin
      username: root
      password: qxp1234
      passwordSet: false
  storage:
    option: minio
    urlExpire: 600
    partExpire: 604800
    launch: false
    storages:
    - name: minio
      protocol: http
      domain: home.qxp.com
      accessKey: Minio
      secretKey: Minio123456
      location: us-east-1
      bucketName: default
  email:
    emails:
    - password: XXX
      host: 邮件服务器地址
      port: 111
      emailfrom: XXX@XXX.com
      username: XXX
      aliasname: 别名
ingress:
  enabled: false
  hosts:
  - host: lowcode.quanxiangyun.com
    paths:
    - fullName: form
      path: /
      svcPort: 80
app:
  kubernetes:
    io:
      name: backend
