kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: keeper
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/version: v1
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .fullName }}
              servicePort: {{ .svcPort }}
        {{- end }}
  {{- end }}