kind: ConfigMap
apiVersion: v1
metadata:
  name: app-center
  namespace: {{ .Values.namespace }}

data:
  config.yml: |
    # model 模式 debug|release
    # debug模式，可以输出更加详细的日志，但是运行速度会减慢
    model: debug
    http:
      port: 80
      #超时秒计算
      readHeaderTimeOut: 15
      writeTimeOut: 600
      maxHeaderBytes: 1048576

    #-------------------mysql配置---------------------
    mysql:
      db: {{ .Values.config.mysql.db }}
      host: {{ .Values.config.mysql.host }}
      user: {{ .Values.config.mysql.user }}
      password: {{ .Values.config.mysql.password }}
      log: {{ .Values.config.mysql.log }}



    #  -------------------- log --------------------
    # comply with zap log specification
    log:
      level: -1
      development: false
      sampling:
        initial: 100
        thereafter: 100
      outputPath:
        - stderr
      errorOutputPath:
        - stderr

    #  -------------------- internalNet --------------------
    internalNet:
      timeout: 20
      maxIdleConns: 10

    #-------------------redis配置-----------------

    redis:
      {{- with .Values.config.redis.addrs }}
      addrs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      username: {{ .Values.config.redis.username }}
      password: {{ .Values.config.redis.password }}

    #----------------内部服务调用Host配置----------
    innerHost:
      structor: "http://structor"
      flow: "http://flow"
      polyAPI: "http://polyapi:9090"
      org: "http://org"
    #----------------导入导出最低版本支持-----------
    compatibleVersion: "0.7.3"
